# Generated by Django 4.2.30 on 2026-05-17 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LottoRound',
            fields=[
                ('round_number', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='회차')),
                ('draw_date', models.DateTimeField(auto_now_add=True, verbose_name='추첨 일시')),
                ('num1', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='번호 1')),
                ('num2', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='번호 2')),
                ('num3', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='번호 3')),
                ('num4', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='번호 4')),
                ('num5', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='번호 5')),
                ('num6', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='번호 6')),
                ('bonus_num', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='보너스 번호')),
                ('is_drawn', models.BooleanField(default=False, verbose_name='추첨 완료 여부')),
            ],
        ),
        migrations.CreateModel(
            name='LottoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('AUTO', '자동'), ('MANUAL', '수동')], max_length=6, verbose_name='구매 방식')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='구매 일시')),
                ('num1', models.PositiveSmallIntegerField(verbose_name='번호 1')),
                ('num2', models.PositiveSmallIntegerField(verbose_name='번호 2')),
                ('num3', models.PositiveSmallIntegerField(verbose_name='번호 3')),
                ('num4', models.PositiveSmallIntegerField(verbose_name='번호 4')),
                ('num5', models.PositiveSmallIntegerField(verbose_name='번호 5')),
                ('num6', models.PositiveSmallIntegerField(verbose_name='번호 6')),
                ('rank', models.PositiveSmallIntegerField(choices=[(0, '미추첨/낙첨'), (1, '1등 (6개 일치)'), (2, '2등 (5개+보너스 일치)'), (3, '3등 (5개 일치)'), (4, '4등 (4개 일치)'), (5, '5등 (3개 일치)')], default=0, verbose_name='당첨 결과')),
                ('lotto_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lotto.lottoround', verbose_name='해당 회차')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='구매자')),
            ],
        ),
    ]
